### ISSUE TITLE
Overwriting DB2 in spesific localization?

### ISSUE THREAD

**Issue by KallarDuskwood** [wowdev/TACT.Net#11]
@barncastle 

Can you make an Example how to overwrite a spesific db2 that has localized strings?
Like Map db2?

**Comment by KallarDuskwood** [comment]
Me and Maxtor found a way todo it. But it reqieres you to change the AddOrUdate Method in the root file alowing to hand over a locale for the file. 

A official way todo this would be neat.

**Comment by barncastle** [comment]
Sorry had a bit of a hiatus on WoW stuff, I see you've sorted this but to follow up:

You can set the Root Locale with `tactRepo.RootFile.LocaleFlags = LocaleFlags.X` before calling `AddOrUpdate` which will set the locale block the new item is added to.

I'll think about adding a specific locale overload once all PRs are done.
