### ISSUE TITLE
Cant open InstallFile, DownloadFile, DownloadSizeFile

### ISSUE THREAD

**Issue by Kallar12** [wowdev/TACT.Net#8]
Hello, I was trying to open a cdn of mine With the attached code. Got this exception. I looked around abit and saw that the md5Hash are the non encypted ones. It works for Patch but not for the rest of the Files.

![image](https://user-images.githubusercontent.com/8331411/59270050-d62c2380-8c50-11e9-85e0-9120eed0ec77.png)

# Build Configuration

root = 7f4cefa93ecc032a4d33d422764a8cf5
install = 1605c706221abbbcfa5b377741331a1c 3efa9ac54fa0cf65dd2dccadfa8bc443
install-size = 17419 16942
download = b9ebb3b90fd4a883e533d7971f67e4f5 78ac34dd31d305813e547c7f83f35cb0
download-size = 37348634 33625598
encoding = f3ef0ad69d177b45740fc9330be44855 eaf3836afbb3846b44d3e9e9034eb4bd
encoding-size = 79670115 79613212
patch = 1c1454badce26849c3157b2fa81fe0e9
patch-size = 2262
patch-config = e36a8e77a07a33b6e3ec3ef980575cc5
build-name = WOW-26972patch7.3.5_Retail
build-uid = wow
build-product = WoW
build-playbuild-installer = ngdptool_casc2
build-partial-priority = e1e6b5f0ad34f2b41e31a54d17e12af8:262144 d4e734c9b348968ab4cabfac2bfc2671:262144 65f799910a118ad61088faf0b92d5ba2:262144 730e23767fd7d381c0daa673059eeca7:262144 650277c63d68542d65b71495728dee1f:1048576 11fbfa9bab88eef295c04d91a7b2fb1f:262144 f3e2e50a087f9e94a478ee3b27faecc3:262144 14ad5d0809af4e31bb9a5ffdc889f437:1048576 39f7dd51abccd53697693ecc9fe3d46e:262144 5cc09f2a9a89f9a5341153d105c96edc:262144 4c03523e1e3fd7ccdde16b29bbc22a3e:262144 ea05c97c414b7d5e43f7812183f99ad9:262144 2485e3a1ab35d28f4b770775fbaf8db8:262144 890fe992fd5c0da7f32fea48070ead69:1048576

**Comment by barncastle** [comment]
This is lack of documentation/information on how TACT works on my part - sorry.

The latest build now exposes the EKeys within the config directly (if available) which will work with the above code - `ConfigContainer.InstallEKey`.

For older builds these keys may not be available so you will need to query the Encoding file for the EKey e.g.
```c#
// use the MD5 hash (CKey) to get the CKeyEntry from the Encoding
tactRepo.EncodingFile.TryGetCKeyEntry(tactRepo.ConfigContainer.InstallMD5, out var installCEntry);

// open the file using the EKey from the CKeyEntry
var installEKey = installCEntry.EKey; // <-- this is the filename
var installFile = new InstallFile(tactRepo.BaseDirectory, installEKey);
```
